# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170419_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='useremail',
            field=models.EmailField(blank=True, max_length=100, verbose_name='邮件地址'),
        ),
    ]
