# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment_useremail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='username',
            field=models.CharField(max_length=30, verbose_name='您的昵称'),
        ),
    ]
