# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 09:10
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='text',
            field=DjangoUeditor.models.UEditorField(verbose_name='正文'),
        ),
    ]
